global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'os-experiment-a'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-a:8000']
        labels:
            version: 'A'

  - job_name: 'os-experiment-b'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-b:8000']
        labels:
            version: 'B'
